# Generated by Django 3.2 on 2022-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.IntegerField()),
                ('sector', models.CharField(max_length=200)),
                ('accreditation_level', models.CharField(max_length=100)),
            ],
        ),
    ]
